# Generated by Django 3.1.2 on 2024-12-01 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('batch_no', models.CharField(max_length=200)),
                ('selling_price', models.FloatField(null=True)),
                ('stock', models.IntegerField()),
                ('date_pack', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField()),
                ('reorder_level', models.FloatField()),
            ],
            options={
                'verbose_name': 'Drug',
                'verbose_name_plural': 'Drugs',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('expiry_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
            },
        ),
        migrations.CreateModel(
            name='Stocked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('number_added', models.IntegerField()),
                ('total', models.IntegerField(null=True)),
                ('drug_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventory.drug')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Addition',
                'verbose_name_plural': 'Stock Additions',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sold', models.DateField(default=django.utils.timezone.now)),
                ('customer', models.CharField(blank=True, max_length=200, null=True)),
                ('sale_price', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('drug_sold', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventory.drug')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.AddField(
            model_name='drug',
            name='measurement_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Inventory.measurement'),
        ),
    ]
