# Generated by Django 3.1.2 on 2024-12-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20241201_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='date_pack',
        ),
        migrations.AddField(
            model_name='drug',
            name='dose_pack',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
