# Generated by Django 3.1.2 on 2024-12-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_auto_20241203_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='remaining_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
