# Generated by Django 3.1.2 on 2025-01-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_lockedproduct_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocked',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
