# Generated by Django 3.1.2 on 2025-01-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_auto_20250101_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_sold',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
