# Generated by Django 3.1.2 on 2025-01-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0010_sale_batch_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sale_price',
        ),
    ]
