# Generated by Django 4.2.17 on 2025-01-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0012_auto_20250109_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='drug_sold',
            field=models.CharField(max_length=200),
        ),
    ]
