# Generated by Django 4.2.17 on 2025-01-22 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0015_marketingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, verbose_name='Item')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock/Quantity')),
                ('issued_to', models.CharField(max_length=255, verbose_name='Issued To')),
                ('quantity_issued', models.PositiveIntegerField(verbose_name='Quantity Issued')),
                ('date_issued', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Issued')),
            ],
            options={
                'verbose_name': 'Issued Item',
                'verbose_name_plural': 'Issued Items',
                'ordering': ['-date_issued'],
            },
        ),
    ]
