# Generated by Django 4.2.17 on 2025-01-23 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventory', '0016_issueditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueditem',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_items', to=settings.AUTH_USER_MODEL, verbose_name='Issued By'),
        ),
        migrations.AlterField(
            model_name='lockedproduct',
            name='locked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
