# Generated by Django 4.2.17 on 2025-01-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0017_issueditem_issued_by_alter_lockedproduct_locked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
