# Generated by Django 4.2.17 on 2025-03-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0019_pickinglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cannister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('batch_no', models.CharField(max_length=100, unique=True)),
                ('stock', models.PositiveIntegerField()),
                ('litres', models.CharField(max_length=255)),
            ],
        ),
    ]
