# Generated by Django 4.2.17 on 2025-03-02 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventory', '0020_cannister'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedCannister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('batch_no', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('action', models.BooleanField(default=False)),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_by', to=settings.AUTH_USER_MODEL)),
                ('staff_on_duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
