# Generated by Django 4.2.17 on 2025-03-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0021_issuedcannister'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedcannister',
            name='balance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
