# Generated by Django 4.2.17 on 2025-03-08 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0022_issuedcannister_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedcannister',
            name='date_returned',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
